# Generated by Django 2.1.4 on 2018-12-31 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contractor_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_scope',
            field=models.CharField(choices=[('I', 'Instalación Imagen'), ('T', 'Instalación Tanques'), ('C', 'Consuloría')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_zone',
            field=models.CharField(choices=[('N', 'Norte'), ('C', 'Centro'), ('S', 'Sur')], default='N', max_length=1),
        ),
    ]
